export type Power = {
  power_id: number;
  name: string;
  framework_id: string | null;
  powerset_id: string | null;
  tier: number | null;
  power_type?: string | null;
  POWER_TYPE?: string | null;
  Power_Type?: string | null;
  activation_type?: string | null;
  activation_time?: number | string | null;
  max_duration?: number | string | null;
  tick_rate?: number | string | null;
  cooldown?: number | string | null;
  cost?: number | string | null;
  damage_values?: number | string | null;
  healing_values?: number | string | null;
  control_values?: number | string | null;
  damage_type?: string[] | string | null;
  damage_types?: string[] | string | null;
  source?: string[] | string | null;
  tooltip?: string | null;
  range_tags?: string[];
  apply_tag?: string[] | string | null;
  refresh_tag?: string[] | string | null;
  synergy_tag?: string[] | string | null;
  filter_tag?: string[] | string | null;
  scaling_stats?: string[];
  advantages: number[];
  icon_override?: string | null;
  power_dependency?: number[];
  is_disabled?: boolean;
  is_legacy?: boolean;
};
